# Generated by Django 4.2.1 on 2024-08-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('website', 'Website'), ('github', 'Github'), ('linkedin', 'LinkedIn'), ('x', 'X'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('category', 'link')},
            },
        ),
    ]
