# Generated by Django 4.2.1 on 2024-08-25 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_alter_profilelinks_category_alter_profilelinks_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilelinks',
            old_name='link',
            new_name='github_link',
        ),
        migrations.AlterUniqueTogether(
            name='profilelinks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='linkedin_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='personal_website_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilelinks',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profilelinks',
            name='category',
        ),
    ]
