# Generated by Django 4.2.1 on 2024-07-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_alter_images_image_blogpost_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
